### ISSUE TITLE
Seitenmenü Icon

### ISSUE THREAD

**Issue by blubablub** [okinoby/Okinoby_pro#32]
Es soll ein Icon auf der linken Seite des Headers angezeigt werden das verdeutlicht, dass es ein Seitenmenü gibt. (die typischen "drei Striche" die in jeder App vorhanden sind)

**Comment by Sascha14** [comment]
Auf manchen Seiten wäre dann zwei Buttons auf der linken Seite. Einmal der neuen Menü-Button und der Zurück-Button. Könnte man nicht auf der rechten Seite den Menü-Button durch den neuen Menü-Icon-Button ersetzt werden?

**Comment by blubablub** [comment]
Ja, der rechte kann weg, aber dann muss der linke, wenn es eine Zurück-Button gibt, kein Menü, sondern ein Zurück-Button sein, sonst funktioniert die Navigation unter iOS nicht.

**Comment by Sascha14** [comment]
Wurde angepasst.
