### ISSUE TITLE
Improve Header

### ISSUE THREAD

**Issue by blubablub** [okinoby/Okinoby_pro#36]
Der Header der App sollte verbessert werden.
Dazu gehören z.B. unter anderem:
-Menü Button entfernen
-Zurück Button nur anzeigen wenn er nötig ist
-Seitenmenü Icon

**Comment by Sascha14** [comment]
- Menü Button entfernt
- Seitenmenü Icon hinzugefügt.

Bei welchen Views ist der Zurück Button z.B. unnötig?

**Comment by blubablub** [comment]
Also, der Menübutton sollte auf die linke Seite, weil sich ja auch das Menü öffnet.
Ich würde vorschlagen, dass der zurück Button eigentlich bei jeder außer dem ersten Menüpunkt da sein sollte, da die Navigation sonst nicht funktioniert. 
Wie gesagt, bei IOS gibt es ja keine Zurück Button. 
BTW:
Beim Verhalten im Notfall fehlt noch bei einigen Menüpunkten der Zurück Button. Meistens nach ca 3-4 Untermenü.

**Comment by Sascha14** [comment]
Das betrifft aber dann nur die erste View oder? Da du ja bereits gestern bei #32 gesagt hattest dass der Menü Button auf der rechten Seite durch dass neue Icon ersetzt wird.
Danke für die Erinnerung dass hät ich jetzt fast vergessen^^.

**Comment by blubablub** [comment]
Ne, das sollte bei jeder so sein. 
Auf der Hauptziel der Menübutton, sonst zurück. 
Vlt hab ich mich da falsch ausgedrückt. 
Ich habe eigentlich Gemeinde, dass der alte rechts weg soll und der neue links hin. 
Also, nur Menübutton links. 
Außer wenn er ein zurück Button wird ^^

**Comment by Sascha14** [comment]
Jetzt habs ich erst richtig verstanden... es gibt immer nur einen Button auf der linken Seite. Falls er kein zurück-Button ist wird es ein Menü-Button. Mein Gedanken war halt derjenige, dass man im Verhalten im Notfall men stellenweise schon sehr tief absteigen kann und das manuelle zurück drücken zu lange dauert. Des Wegen hätte ich trotzdem rechts einen Menü-Button machen wollen. Aber andererseits kommt man jederzeit auch durch einen Swipe ins Menü^^...ich werds heut noch abändern.
